modLoader='javafml'
loaderVersion="${forgeversionrange}"
license="${license}"

issueTrackerURL="${issues}"

[[mods]]
    modId="${modid}"
    version="${version}"
    displayName="${name}"
    # A URL to query for updates for this mod. See the JSON update specification https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/
    #updateJSONURL="https://change.me.example.invalid/updates.json" #optional
    displayURL="${distribution}"
    logoFile="${logo}"
    credits="${credits}"
    authors="${author}"
    description='''${description}'''

    [[dependencies.${modid}]]
        modId='forge'
        mandatory=true
        versionRange="${forgeversionrange}"
        ordering='NONE'
        side='BOTH'

    [[dependencies.${modid}]]
        modId='minecraft'
        mandatory=true
        versionRange='${minecraftversionrange}'
        ordering='NONE'
        side='BOTH'
